spring:
  application:
    name: fat-measurements-backend

  jpa:
    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19981002520qq
    url: jdbc:mysql://localhost:3306/fat_measurements_backend?useSSL=false&characterEncoding=utf-8
