# 网易对象存储服务nos
nos:
  accessKey: 32af146fa7c0457fbe4345a98cc753ca
  secretKey: 16a9afdc8e5b4ac4bd483f2c75eb2fc0
  endPoint: nos-eastchina1.126.net
  bucket_head_portrait: bucket-head-portrait
  bucket_B_ultrasonic: bucket-B-ultrasonic

# 阿里对象存储服务oss
oss:
  accessKey: LTAIGRZBvpO6FEsL
  secretKey: uC8NnYIpmMd9TagI3rknYDdo5HiyQJ
  endPoint: oss-cn-beijing.aliyuncs.com
  bucket_head_portrait: bucket-head-portrait
  bucket_B_ultrasonic: bucket-b-ultrasonic

normal_corePoolSize: 10
normal_maxPoolSize: 50

spring:
  application:
    name: fat-measurements-backend

  jpa:
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19981002520qq
    url: jdbc:mysql://localhost:3306/fat_measurements_backend?useSSL=false&characterEncoding=utf-8

  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  redis:
    host: localhost
    port: 6379